pub mod adapter;
pub mod attention;
pub mod board;
pub mod board_config;
pub mod board_watch;
pub mod cli;
pub mod client;
pub mod copy;
pub mod dashboard;
// The extracted crates keep their old paths so every `crate::detect::…` and
// `crate::terminal::…` call site in this crate resolves unchanged.
pub use dock_detect as detect;
pub use dock_pty::{clipboard, terminal};
pub mod discovery;
pub mod dispatch;
pub mod files;
pub mod git;
pub mod hook;
pub mod keymap;
pub mod layout;
pub mod model;
pub mod paths;
pub mod picker;
pub mod protocol;
pub mod queue;
pub mod runtime;
pub mod server;
pub mod storage;
pub mod theme;
pub mod verdict;
